// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories;

#nullable disable

namespace StoreApp.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20250523194728_MayInit")]
    partial class MayInit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.36");

            modelBuilder.Entity("Entities.Models.CartLine", b =>
                {
                    b.Property<int>("CartLineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrderID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("CartLineID");

                    b.HasIndex("OrderID");

                    b.HasIndex("ProductID");

                    b.ToTable("CartLine");
                });

            modelBuilder.Entity("Entities.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Book"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Electronic"
                        });
                });

            modelBuilder.Entity("Entities.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("GiftWrap")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Line2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Line3")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Shipped")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrderID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShowCase")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            CategoryID = 2,
                            ImageUrl = "/images/a.jpg",
                            ProductName = "Computer",
                            ProductPrice = 17000m,
                            ShowCase = false,
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 2,
                            CategoryID = 2,
                            ImageUrl = "/images/a.jpg",
                            ProductName = "Keyboard",
                            ProductPrice = 1000m,
                            ShowCase = false,
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 3,
                            CategoryID = 2,
                            ImageUrl = "/images/a.jpg",
                            ProductName = "Mouse",
                            ProductPrice = 500m,
                            ShowCase = false,
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 4,
                            CategoryID = 2,
                            ImageUrl = "/images/a.jpg",
                            ProductName = "Monitor",
                            ProductPrice = 7000m,
                            ShowCase = false,
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 5,
                            CategoryID = 2,
                            ImageUrl = "/images/a.jpg",
                            ProductName = "Deck",
                            ProductPrice = 1500m,
                            ShowCase = false,
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 6,
                            CategoryID = 1,
                            ImageUrl = "/images/a.jpg",
                            ProductName = "History",
                            ProductPrice = 25m,
                            ShowCase = false,
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 7,
                            CategoryID = 1,
                            ImageUrl = "/images/a.jpg",
                            ProductName = "Hamlet",
                            ProductPrice = 45m,
                            ShowCase = false,
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 8,
                            CategoryID = 2,
                            ImageUrl = "/images/a.jpg",
                            ProductName = "Xp-Pen",
                            ProductPrice = 100m,
                            ShowCase = true,
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 9,
                            CategoryID = 1,
                            ImageUrl = "/images/a.jpg",
                            ProductName = "Mobile Phone",
                            ProductPrice = 15000m,
                            ShowCase = true,
                            Summary = ""
                        },
                        new
                        {
                            ProductID = 10,
                            CategoryID = 2,
                            ImageUrl = "/images/a.jpg",
                            ProductName = "Tablet",
                            ProductPrice = 5000m,
                            ShowCase = true,
                            Summary = ""
                        });
                });

            modelBuilder.Entity("Entities.Models.CartLine", b =>
                {
                    b.HasOne("Entities.Models.Order", null)
                        .WithMany("Lines")
                        .HasForeignKey("OrderID");

                    b.HasOne("Entities.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.HasOne("Entities.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Entities.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Entities.Models.Order", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
